export const VIEW_STATISTICS_REPOSITORY = Symbol('VIEW_STATISTICS_REPOSITORY');
export const RECORD_PUBLIC_VIEW = Symbol('RECORD_PUBLIC_VIEW');
export const GET_RESTAURANT_VIEW_STATISTICS = Symbol('GET_RESTAURANT_VIEW_STATISTICS');
export const RETAIN_VIEW_EVENTS = Symbol('RETAIN_VIEW_EVENTS');
