import {
  Inter,
  Lato,
  Libre_Baskerville,
  Merriweather,
  Montserrat,
  Nunito,
  Open_Sans,
  Oswald,
  Playfair_Display,
  Poppins,
  Raleway,
  Roboto,
} from 'next/font/google';

import type { MenuFont } from '@/shared/menu-style';

// The 12 families a published menu can use (§E7). Imported only by the public
// menu and by the template preview: the rest of the panel never loads them.
// next/font needs literal arguments, so these calls cannot be factored out.
// `preload: false`: a menu uses one family, so preloading all twelve would
// waste bandwidth; the one in use downloads when its text renders.

const inter = Inter({ display: 'swap', preload: false, subsets: ['latin'] });
const roboto = Roboto({ display: 'swap', preload: false, subsets: ['latin'] });
const openSans = Open_Sans({ display: 'swap', preload: false, subsets: ['latin'] });
const lato = Lato({ display: 'swap', preload: false, subsets: ['latin'], weight: ['400', '700'] });
const montserrat = Montserrat({ display: 'swap', preload: false, subsets: ['latin'] });
const poppins = Poppins({ display: 'swap', preload: false, subsets: ['latin'], weight: ['400', '600', '700'] });
const playfairDisplay = Playfair_Display({ display: 'swap', preload: false, subsets: ['latin'] });
const merriweather = Merriweather({ display: 'swap', preload: false, subsets: ['latin'] });
const oswald = Oswald({ display: 'swap', preload: false, subsets: ['latin'] });
const raleway = Raleway({ display: 'swap', preload: false, subsets: ['latin'] });
const nunito = Nunito({ display: 'swap', preload: false, subsets: ['latin'] });
const libreBaskerville = Libre_Baskerville({ display: 'swap', preload: false, subsets: ['latin'] });

const FONTS: Record<MenuFont, { style: { fontFamily: string } }> = {
  Inter: inter,
  Lato: lato,
  'Libre Baskerville': libreBaskerville,
  Merriweather: merriweather,
  Montserrat: montserrat,
  Nunito: nunito,
  'Open Sans': openSans,
  Oswald: oswald,
  'Playfair Display': playfairDisplay,
  Poppins: poppins,
  Raleway: raleway,
  Roboto: roboto,
};

/** The CSS font-family of a menu family, as generated by next/font, with its fallback. */
export function menuFontFamily(font: MenuFont): string {
  return FONTS[font].style.fontFamily;
}
