import type { Metadata } from 'next';

import { buttonClasses, ButtonLink } from '@/components/ui/button';
import { CopyButton } from '@/components/ui/copy-button';
import { Card, Notice } from '@/components/ui/surfaces';
import { requireOwnerPage } from '@/server/next/page-auth';
import { ensureRestaurantQr } from '@/server/qr';
import { QR_NOT_CONFIGURED_MESSAGE } from '@/shared/qr';

export const metadata: Metadata = { title: 'Código QR' };

/** Opening this page is what generates the QR the first time (§E9). */
export default async function QrPage() {
  const { restaurant } = await requireOwnerPage();
  const qr = await ensureRestaurantQr(restaurant.id, restaurant.slug);

  return (
    <div className="grid max-w-3xl gap-6">
      <div className="grid gap-1">
        <h1 className="m-0 font-display text-3xl font-semibold tracking-tight">Código QR</h1>
        <p className="m-0 text-[15px] text-ink-soft">
          Imprímelo en tus mesas: lleva a tus clientes directo a tu carta digital.
        </p>
      </div>

      {qr ? (
        <Card className="grid gap-6 p-6 sm:grid-cols-[auto_1fr] sm:items-start">
          {/* eslint-disable-next-line @next/next/no-img-element -- inline SVG generated by the server */}
          <img
            alt={`Código QR de la carta de ${restaurant.name}`}
            className="h-56 w-56 justify-self-center rounded-control border border-line bg-white sm:h-64 sm:w-64"
            height={256}
            src={`data:image/svg+xml;base64,${Buffer.from(qr.svg).toString('base64')}`}
            width={256}
          />
          <div className="grid min-w-0 gap-4">
            <div className="grid gap-1">
              <h2 className="m-0 text-sm font-semibold text-ink-soft">Dirección de tu carta</h2>
              <p className="m-0 font-mono text-[15px] break-all text-ink" data-testid="url-qr">
                {qr.payload}
              </p>
            </div>
            <div className="flex flex-wrap items-start gap-3">
              <a className={buttonClasses('primary')} download href="/api/qr/png">
                Descargar PNG
              </a>
              <a className={buttonClasses('secondary')} download href="/api/qr/svg">
                Descargar SVG
              </a>
              <CopyButton
                copiedMessage="Enlace copiado."
                failedMessage="No pudimos copiar el enlace. Cópialo a mano."
                label="Copiar enlace"
                text={qr.payload}
              />
              <ButtonLink href={`/${restaurant.slug}`} rel="noopener" target="_blank" variant="secondary">
                Abrir carta pública
              </ButtonLink>
            </div>
            <p className="m-0 text-sm text-ink-soft">
              Este QR no cambia aunque edites tu carta o el nombre del restaurante.
            </p>
          </div>
        </Card>
      ) : (
        <Notice tone="warning">{QR_NOT_CONFIGURED_MESSAGE}</Notice>
      )}
    </div>
  );
}
