export const MENU_EXTRACTION_GATEWAY = Symbol('MENU_EXTRACTION_GATEWAY');
export const MENU_PUBLICATION_REPOSITORY = Symbol('MENU_PUBLICATION_REPOSITORY');
export const DIGITIZE_MENU = Symbol('DIGITIZE_MENU');
export const GET_OWNED_MENU = Symbol('GET_OWNED_MENU');
export const PUBLISH_MENU = Symbol('PUBLISH_MENU');
export const SET_MENU_TEMPLATE = Symbol('SET_MENU_TEMPLATE');
