export const MENU_EXTRACTION_GATEWAY = Symbol('MENU_EXTRACTION_GATEWAY');
export const MENU_PUBLICATION_REPOSITORY = Symbol('MENU_PUBLICATION_REPOSITORY');
export const DIGITIZE_MENU = Symbol('DIGITIZE_MENU');
export const GET_OWNED_MENU = Symbol('GET_OWNED_MENU');
